-- MySQL Script generated by MySQL Workbench
-- Wed Nov 11 11:03:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gedung_negara
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gedung_negara
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gedung_negara` DEFAULT CHARACTER SET utf8mb4 ;
USE `gedung_negara` ;

-- -----------------------------------------------------
-- Table `gedung_negara`.`failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedung_negara`.`failed_jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gedung_negara`.`gedung_ketegori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedung_negara`.`gedung_ketegori` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(64) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gedung_negara`.`gedung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedung_negara`.`gedung` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_gedung_kategori` INT(11) NULL DEFAULT NULL,
  `nama` VARCHAR(255) NOT NULL,
  `alamat` VARCHAR(255) NULL DEFAULT NULL,
  `bujur_timur` DOUBLE NULL DEFAULT NULL,
  `lintang_selatan` DOUBLE NULL DEFAULT NULL,
  `legalitas` VARCHAR(32) NULL DEFAULT NULL,
  `tipe_pemilik` VARCHAR(32) NULL DEFAULT NULL,
  `alas_hak` VARCHAR(32) NULL DEFAULT NULL,
  `luas_lahan` DOUBLE NULL DEFAULT NULL,
  `jumlah_lantai` INT(11) NULL DEFAULT NULL,
  `luas` DOUBLE NULL DEFAULT NULL,
  `tinggi` DOUBLE NULL DEFAULT NULL,
  `kompleks` VARCHAR(32) NULL DEFAULT NULL,
  `kepadatan` VARCHAR(64) NULL DEFAULT NULL,
  `permanensi` VARCHAR(32) NULL DEFAULT NULL,
  `tkt_resiko_kebakaran` VARCHAR(32) NULL DEFAULT NULL,
  `penangkal_petir` VARCHAR(32) NULL DEFAULT NULL,
  `struktur_bawah` VARCHAR(255) NULL DEFAULT NULL,
  `struktur_bangunan` VARCHAR(255) NULL DEFAULT NULL,
  `struktur_atap` VARCHAR(255) NULL DEFAULT NULL,
  `kode_provinsi` VARCHAR(45) NULL DEFAULT NULL,
  `kode_kabupaten` VARCHAR(45) NULL DEFAULT NULL,
  `kode_kecamatan` VARCHAR(45) NULL DEFAULT NULL,
  `kode_kelurahan` VARCHAR(45) NULL DEFAULT NULL,
  `kdb` VARCHAR(255) NULL DEFAULT NULL,
  `klb` VARCHAR(255) NULL DEFAULT NULL,
  `kdh` VARCHAR(255) NULL DEFAULT NULL,
  `gsb` VARCHAR(255) NULL DEFAULT NULL,
  `rth` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_gedung_kategori_idx` (`id_gedung_kategori` ASC),
  CONSTRAINT `fk_gedung_kategori`
    FOREIGN KEY (`id_gedung_kategori`)
    REFERENCES `gedung_negara`.`gedung_ketegori` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 117
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gedung_negara`.`provinsi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedung_negara`.`provinsi` (
  `id_prov` CHAR(2) NOT NULL,
  `nama` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_prov`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gedung_negara`.`kota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedung_negara`.`kota` (
  `id_kota` CHAR(4) NOT NULL,
  `id_prov` CHAR(2) NOT NULL,
  `nama` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_kota`),
  INDEX `regencies_province_id_index` (`id_prov` ASC),
  CONSTRAINT `regencies_province_id_foreign`
    FOREIGN KEY (`id_prov`)
    REFERENCES `gedung_negara`.`provinsi` (`id_prov`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gedung_negara`.`kecamatan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedung_negara`.`kecamatan` (
  `id_kec` CHAR(7) NOT NULL,
  `id_kota` CHAR(4) NOT NULL,
  `nama` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_kec`),
  INDEX `districts_id_index` (`id_kota` ASC),
  CONSTRAINT `districts_regency_id_foreign`
    FOREIGN KEY (`id_kota`)
    REFERENCES `gedung_negara`.`kota` (`id_kota`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gedung_negara`.`kelurahan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedung_negara`.`kelurahan` (
  `id_kel` CHAR(10) NOT NULL,
  `id_kec` CHAR(7) NOT NULL,
  `nama` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_kel`),
  INDEX `villages_district_id_index` (`id_kec` ASC),
  CONSTRAINT `villages_district_id_foreign`
    FOREIGN KEY (`id_kec`)
    REFERENCES `gedung_negara`.`kecamatan` (`id_kec`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gedung_negara`.`kerusakan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedung_negara`.`kerusakan` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_gedung` INT(11) NOT NULL,
  `tanggal` DATETIME NOT NULL,
  `detail_json` TEXT NULL DEFAULT NULL,
  `sketsa_denah` VARCHAR(255) NULL DEFAULT NULL,
  `gambar_bukti` VARCHAR(255) NULL DEFAULT NULL,
  `opd` VARCHAR(45) NULL DEFAULT NULL,
  `nomor_aset` VARCHAR(45) NULL DEFAULT NULL,
  `petugas_survei1` VARCHAR(45) NULL DEFAULT NULL,
  `petugas_survei2` VARCHAR(45) NULL DEFAULT NULL,
  `petugas_survei3` VARCHAR(45) NULL DEFAULT NULL,
  `perwakilan_opd1` VARCHAR(45) NULL DEFAULT NULL,
  `perwakilan_opd2` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_kerusakan_gedung_idx` (`id_gedung` ASC),
  CONSTRAINT `fk_kerusakan_gedung`
    FOREIGN KEY (`id_gedung`)
    REFERENCES `gedung_negara`.`gedung` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 66
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gedung_negara`.`satuan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedung_negara`.`satuan` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(16) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gedung_negara`.`komponen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedung_negara`.`komponen` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(64) NOT NULL,
  `bobot` DOUBLE NULL DEFAULT NULL,
  `id_satuan` INT(11) NULL DEFAULT NULL,
  `id_parent` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_kompoenen_parent_idx` (`id_parent` ASC),
  INDEX `fk_kompoenen_satuan_idx` (`id_satuan` ASC),
  CONSTRAINT `fk_kompoenen_parent`
    FOREIGN KEY (`id_parent`)
    REFERENCES `gedung_negara`.`komponen` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_kompoenen_satuan`
    FOREIGN KEY (`id_satuan`)
    REFERENCES `gedung_negara`.`satuan` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 386
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gedung_negara`.`komponen_opsi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedung_negara`.`komponen_opsi` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `opsi` VARCHAR(255) NOT NULL,
  `nilai` INT(11) NOT NULL DEFAULT 0 COMMENT 'persentase',
  `id_komponen` INT(11) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `delete_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_komponen_opsi_komponen_idx` (`id_komponen` ASC),
  CONSTRAINT `fk_komponen_opsi_komponen`
    FOREIGN KEY (`id_komponen`)
    REFERENCES `gedung_negara`.`komponen` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gedung_negara`.`kerusakan_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedung_negara`.`kerusakan_detail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_kerusakan` INT(11) NOT NULL,
  `id_komponen` INT(11) NOT NULL,
  `jumlah` INT(11) NULL DEFAULT NULL,
  `id_komponen_opsi` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_kerusakan_detail_kerusakan_idx` (`id_kerusakan` ASC),
  INDEX `fk_kerusakan_detail_komponen_idx` (`id_komponen` ASC),
  INDEX `fk_kerusakan_detail_komponen_opsi_idx` (`id_komponen_opsi` ASC),
  CONSTRAINT `fk_kerusakan_detail_kerusakan`
    FOREIGN KEY (`id_kerusakan`)
    REFERENCES `gedung_negara`.`kerusakan` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_kerusakan_detail_komponen`
    FOREIGN KEY (`id_komponen`)
    REFERENCES `gedung_negara`.`komponen` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_kerusakan_detail_komponen_opsi`
    FOREIGN KEY (`id_komponen_opsi`)
    REFERENCES `gedung_negara`.`komponen_opsi` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 160
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gedung_negara`.`kerusakan_klasifikasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedung_negara`.`kerusakan_klasifikasi` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_kerusakan_detail` INT(11) NOT NULL,
  `jumlah` INT(11) NOT NULL DEFAULT 0,
  `klasifikasi` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_kerusakan_klasifikasi_k_detail_idx` (`id_kerusakan_detail` ASC),
  CONSTRAINT `fk_kerusakan_klasifikasi_k_detail`
    FOREIGN KEY (`id_kerusakan_detail`)
    REFERENCES `gedung_negara`.`kerusakan_detail` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 104
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gedung_negara`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedung_negara`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gedung_negara`.`kerusakan_surveyor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedung_negara`.`kerusakan_surveyor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_kerusakan` INT(11) NOT NULL,
  `id_user` BIGINT(20) NOT NULL,
  `users_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_kerusakan_surveyor_kerusakan_idx` (`id_kerusakan` ASC),
  INDEX `fk_kerusakan_surveyor_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_kerusakan_surveyor_kerusakan`
    FOREIGN KEY (`id_kerusakan`)
    REFERENCES `gedung_negara`.`kerusakan` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_kerusakan_surveyor_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `gedung_negara`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 69
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `gedung_negara`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedung_negara`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gedung_negara`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedung_negara`.`permissions` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `name_alias` VARCHAR(255) NULL DEFAULT NULL,
  `guard_name` VARCHAR(255) NOT NULL,
  `category` ENUM('default', 'role', 'gedung', 'satuan', 'komponen', 'kerusakan', 'users', 'other') NULL DEFAULT 'default',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 71
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gedung_negara`.`model_has_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedung_negara`.`model_has_permissions` (
  `permission_id` BIGINT(20) UNSIGNED NOT NULL,
  `model_type` VARCHAR(255) NOT NULL,
  `model_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`permission_id`, `model_id`, `model_type`),
  INDEX `model_has_permissions_model_id_model_type_index` (`model_id` ASC, `model_type` ASC),
  CONSTRAINT `model_has_permissions_permission_id_foreign`
    FOREIGN KEY (`permission_id`)
    REFERENCES `gedung_negara`.`permissions` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gedung_negara`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedung_negara`.`roles` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `guard_name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gedung_negara`.`model_has_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedung_negara`.`model_has_roles` (
  `role_id` BIGINT(20) UNSIGNED NOT NULL,
  `model_type` VARCHAR(255) NOT NULL,
  `model_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`role_id`, `model_id`, `model_type`),
  INDEX `model_has_roles_model_id_model_type_index` (`model_id` ASC, `model_type` ASC),
  CONSTRAINT `model_has_roles_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `gedung_negara`.`roles` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gedung_negara`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedung_negara`.`password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gedung_negara`.`role_has_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedung_negara`.`role_has_permissions` (
  `permission_id` BIGINT(20) UNSIGNED NOT NULL,
  `role_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`permission_id`, `role_id`),
  INDEX `role_has_permissions_role_id_foreign` (`role_id` ASC),
  CONSTRAINT `role_has_permissions_permission_id_foreign`
    FOREIGN KEY (`permission_id`)
    REFERENCES `gedung_negara`.`permissions` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `role_has_permissions_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `gedung_negara`.`roles` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
